# Whether or not to enable the trapdoor logging feature
enabled: true
# The MySQL database connection details
mysql:
    host: localhost
    port: 3306
    name: database
    user: root
    password: password
